spring.application.name=whats-aiassist-code

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/userdb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.threads.virtual.enabled=true

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:false}
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

app.security.reader.username=${APP_SECURITY_READER_USERNAME:reader}
app.security.reader.password=${APP_SECURITY_READER_PASSWORD:reader123}
app.security.writer.username=${APP_SECURITY_WRITER_USERNAME:admin}
app.security.writer.password=${APP_SECURITY_WRITER_PASSWORD:admin123}

app.whatsapp.api-version=${APP_WHATSAPP_API_VERSION:v23.0}
app.whatsapp.phone-number-id=${APP_WHATSAPP_PHONE_NUMBER_ID:1033764916480542}
app.whatsapp.access-token=${APP_WHATSAPP_ACCESS_TOKEN:EAANJGeDsmMYBQpQrsP1LafZCfUN3RiUFMW3s8XTK5t3O1RpxLpSxlJoIZCdraoX4f1kabP4n1AmI6uy5IixvSa13gXqsUpAcTJpwe2GN1XJa3jG9H8mTtZAILNtnLRHF2ZCdkadZCkHYQ9VMAxuwCC5aGOPSKerHMhRT0JWKiLMIirV0axJ7C5UjfaiOgQLo75wZDZD}
app.whatsapp.verify-token=${APP_WHATSAPP_VERIFY_TOKEN:test_whats}
