spring.application.name=whats-aiassist-code

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/userdb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.threads.virtual.enabled=true

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:false}
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

app.security.reader.username=${APP_SECURITY_READER_USERNAME:reader}
app.security.reader.password=${APP_SECURITY_READER_PASSWORD:reader123}
app.security.writer.username=${APP_SECURITY_WRITER_USERNAME:admin}
app.security.writer.password=${APP_SECURITY_WRITER_PASSWORD:admin123}
